version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /usr/share/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elasticdata:/var/lib/elasticsearch/data
    networks:
      - elknetwork
  kibana:
    image: kibana:7.8.0
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    volumes:
      - /usr/share/kibana/kibana.yml:/etc/kibana/kibana.yml
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  logstash:
    image: logstash:7.8.0
    container_name: logstash
    hostname: logstash
    environment:
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: "elastic"
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: "elasticpasswd"
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - /usr/share/logstash/pipeline:/etc/logstash/pipeline/
      - /usr/share/logstash/logstash.yml:/etc/logstash/logstash.yml
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - elknetwork

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.0
    container_name: filebeat
    hostname: filebeat
    volumes:
      - ./filebeat.yml:/etc/filebeat/filebeat.yml
        #      - ./nginx/log:/var/log/nginx
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elknetwork
    links:
      - logstash
    depends_on:
      - logstash
      - elasticsearch
      - kibana

networks:
  elknetwork:
    driver: bridge
