---
- name: Ensure kibana dir exists
  file:
    path: "{{ conf_dir }}/kibana"
    state: directory

- name: Copy kibana conf
  template:
    src: kibana.yml.j2
    dest: "{{ conf_dir }}/kibana/kibana.yml"

    #- name: Create a network
    #  docker_network:
    #    name: "{{ network_name }}"
    #
    #- name: Start kibana container
    #  docker_container:
    #    name: "{{ kibana_hostname }}"
    #    image: "{{ kibana_image }}"
    #    volumes:
    #      - "{{ conf_dir }}/kibana:/etc/kibana/kibana.yml:ro"
    #    ports:
    #      - "5601:5601"
    #    networks:
    #      - name: "{{ network_name }}"
    #    log_driver: "{{ log_driver }}"
